version: '3.11'

services:
  db:
    image: postgres
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_DB: postgres

  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db