# Generated by Django 4.0.2 on 2022-04-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
